services:
  redirector:
    image: node:lts-alpine
    working_dir: /app
    entrypoint: npm run start:dev
    depends_on:
      - cache
      - roach1
      - roach2
      - roach3
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    environment:
      - HOST="0.0.0.0"
      - PORT=3000

      - BUS_HOST="rabbit-lb"
      - BUS_PORT=5672
      - BUS_USER="admin"
      - BUS_PASS="admin"
      - BUS_QUEUE="redirector_queue"
    networks:
      - usnet
      - busnet
      - cachenet
    volumes:
      - ./:/app
